### ISSUE TITLE
As a user I want to understand the submission process and its associated tasks

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/gwas-deposition-app#1]
- [ ] GWAS Catalog main page lists a clear link to documentation on the submission process
- [ ] Link should probably be a new category alongside the 6 existing ones (Search, Diagram, etc…)
- [ ] Upon accessing the link, User lands on the Submission page
- [ ] Submission page lists clearly data eligibility criteria, How Tos on the submission process, including how to obtain data eligibility.
- [ ] The platform provides the option to review the schema underpinning the submission template
- [ ] User has the option to 'Download submission template' & ‘Download summary stats template’
- [ ] Platform returns an empty Excel template formatted according to the submission schema

Interaction:
- [ ]  Front: Renders static page
- [ ] Front: On ‘Download template’ actions calls the appropriate endpoint in GWAS Template Creator
